#Configuration#
Plugin:
  #Debug Mode#
  Debug: false

#Reasons not to add special equipmemt#
#If true blocks usage#
Reason:
  Spawner: true
  Egg: true
DropFix:
  #Adds Damages to all drops#
  Damage: true

#When adding enchantments, only allow safe or item specific enchantments#
SafeEnchant:
  Enabled: false

#Allow the generation of ruins in the map#
Ruins:
  Enabled: true
  Chance: 100

#Allow the drop of custom items (custom.yml)#
Custom:
  Only: false
  Enabled: true
  Chance: 1

#Allow the drop of lore items (lore.txt enhancements)#
Lore:
  Enabled: true
  Chance: 5
  EnhanceAmount: 1

#Changing the way that a few things are displayed#
Display:
  TierName: true
  ColorBlind: false
  ItemMaterialExtras: false
  ItemNameFormat: '%randprefix% %randsuffix%'

#Allow the drop of book to "identify" Magic color items#
IdentifyTome:
  Enabled: true
  Chance: 2
SockettedItem:
  Enabled: true
  Chance: 20
  MinimumSockets: 1
  MaximumSockets: 5

#Allow the drop of socket items#
SocketItem:
  Enabled: true
  Chance: 5
  #Whether to set lore on sockets#
  Lore: true
  Items: 
  - Emerald
  - Diamond
  - Skull_Item
  Colors:
  - GREEN
  - RED
  - BLUE

#This is the initial chance to retrieve an item#
Percentages:
  ChancePerSpawn: 3

#If enabled only worlds listed will be affected#
Worlds:
  Enabled: false
  Allowed:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
  
  
  
  
  
version: '4.0.0-B'
options:
  can-drop-socket-gems-on-items: false
  prevent-multiple-name-changes-from-sockets: false
  use-attacker-item-in-hand: true
  use-attacker-armor-equipped: false
  use-defender-item-in-hand: false
  use-defender-armor-equipped: true
  socket-gem-material-ids:
  - DIAMOND
  - EMERALD
  - NETHER_STAR
items:
  socketted-item-socket: '%tiercolor%(Socket)'
  socketted-item-lore:
  - '&7Find a &6Socket Gem&7 to fill a &F%tiercolor%(Socket)&7'
  socket-name: '&6Socket Gem - %socketgem%'
  socket-lore:
  - '&7Right-click while holding this gem'
  - '&7in your hand to begin socketting!'
  - '&8(&8%type%&8)'

