name: APOCRPG
main: com.Plugin.Main.Plugin
version: 0
authors: [WIX0A,unarmed1618]
description: Plugin

commands:
    generateitem:
        description: Allows user to spawn a generated item.
        aliases: [genitem, dd]
        usage: /<command> 
    generateuseful:
        description: Allows user to spawn a useful item.
        aliases: [genuseful, ddu]
        usage: /<command> [type]
        