name: APOCRPG
main: com.Plugin.Main.Plugin
version: 0
authors: [WIX0A,unarmed1618]
description: Plugin

commands:
    apocrpg:
        description: Main command
        aliases: [rpg]
        usage: /apocrpg, /rpg