name: DiabloDrops
main: com.modcrafting.diablodrops.DiabloDrops
version: 2.4.505
website: http://dev.bukkit.org/server-mods/diablodrops/
authors: [Deathmarine,Nunnery]
description: >
             Item Drop/Equip Enhancement Plugin.
loadbefore: [DiabloBosses, Identify, DiabloLoot, DiabloDungeonBridge]
load: STARTUP
             
commands:
    diablodrops:
        description: Allows user to spawn a type of item.
        aliases: [dd, ddrops, diablod]
        usage: /<command> [type]
        permission: diablodrops.dd
permissions:
    diablodrops.dd:
        description: Allows user to spawn a type of item.
        default: op
    diablodrops.debug:    
        description: Allows user to receive debug messages.      
        default: false
    diablodrops.reload:
        description: Allows user to reload the plugin.
        default: op
